[feature] User profile page
MikeVedsted/JoinMe pull request #112
Opened 2020-12-15 13:17 UTC by nannadao

2020-12-15 16:35 UTC, Rostislav013 commented on client/src/pages/ProfilePage/index.tsx
> +  const [profileImage, setProfileImage] = useState('')
Is it possible to make shorter?
Like `const { userId } = match.params` ?

2020-12-15 16:37 UTC, Rostislav013 approved these changes

2020-12-16 08:47 UTC, MikeVedsted requested changes
I don't think your routing and params are working as intended. When I try to run your code with a valid user id, I'm getting undefined responses. 
If I exchange the dynamic user id in `getUserInfo` I get the expected response and the page populates as intended. 
This can be solved by using `useParams `instead of `RouteComponentProps` and removing the `match `prop.

2020-12-16 08:47 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +import { useHistory } from 'react-router-dom'
I would have preferred to use the `useParams` hook from react-router-dom

2020-12-16 08:47 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +  const [profileImage, setProfileImage] = useState('')
Yes. But if it would be refactored to use `useParams` from router-router-dom, it would be `const { userId } = useParams()`

2020-12-16 08:47 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +            <p> {interest} </p>
This is going to look a bit off, when you end up receiving an array. You should iterate of the array to ensure the values display correctly.

2020-12-16 08:47 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
> +  }
Adding element selectors is not correct BEM methodology. 
Technically, your `left `and `right` would also be boxed, not elements.

2020-12-16 08:47 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
> +    margin-bottom: 26px;
Would it make sense to make the column a percentage of the vw and the image relative to the column, instead of hardcoding image sizes?

2020-12-16 08:47 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
> +    border: 1px solid #606060;
please change the color to a theme color

2020-12-16 08:56 UTC, MikeVedsted requested changes

2020-12-16 08:56 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +  const [address, setAddress] = useState('')
Since we do not expect the values to change, it is not necessary to use `useState`.

2020-12-16 21:27 UTC, Rostislav013 commented
> I don't think your routing and params are working as intended. When I try to run your code with a valid user id, I'm getting undefined responses.
> If I exchange the dynamic user id in `getUserInfo` I get the expected response and the page populates as intended.
> This can be solved by using `useParams `instead of `RouteComponentProps` and removing the `match `prop.

After I deleted a row  in db and tried to login/create user it started to work correctly again both ways with `useParam` n match. But I prefer `useParam` too

2020-12-18 04:25 UTC, nannadao commented on client/src/pages/ProfilePage/index.tsx
> +  const [address, setAddress] = useState('')
Please suggest an alternative. We do not have store so I have to create state to store the data that is returned from the API call.

2020-12-18 07:33 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +  const [address, setAddress] = useState('')
I just mean that you could just use constants instead of importing useState and having all the setter functions as unused.

2020-12-18 12:02 UTC, MikeVedsted approved these changes
Much better. There's are some serious issues with the responsivenes though.

2020-12-18 12:02 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +      <Navbar />
we can just put navbar above the routes to avoid rerenders, so no need for it here.

2020-12-18 12:13 UTC, Rostislav013 approved these changes
Coolio

2020-12-22 09:41 UTC, closed without merging