[test] Add user service tests
MikeVedsted/JoinMe pull request #117
Opened 2020-12-15 16:19 UTC by Rostislav013

Welcome to have a look at our page, dear reader :)

Feel free to propose tests to implement.

2020-12-16 10:54 UTC, MarinaFroes requested changes
Please, consider my comments below.

2020-12-16 10:54 UTC, MarinaFroes commented on test/controllers/user.test.ts
> +  it.skip('should get all users', async () => {
Did you need to push commented code and skip this test for a specific reason?
You wouldn't need to disable the rule if you removed the `.skip`.

2020-12-16 10:54 UTC, MarinaFroes commented on test/services/user.test.ts
> +}
This function could also receive an optional user parameter for the cases when you want to create an extra user, like you did in line 66. We did something similar in our fullstack project.
I suggest to use arrow function here as well. `const createUser = async (override?: Partial<User>) => {}`

2020-12-16 10:54 UTC, MarinaFroes commented on test/services/user.test.ts
> +    const user = await db.query('SELECT * FROM userk;')
Wouldn't it be the case to use the `createUser` function here?
And when checking if the user was created, shouldn't we use a user service to find the created user?

2020-12-16 10:54 UTC, MarinaFroes commented on test/services/user.test.ts
> +    )
As I mentioned before, if we pass a user param to `createUser`, you can use it here as well to create the second user.

2020-12-16 10:54 UTC, MarinaFroes commented on test/services/user.test.ts
> +    const user = await createUser()
It really shouldn't get a **non-existing book** in our user table. 😄

2020-12-16 10:54 UTC, MarinaFroes commented on test/services/user.test.ts
> +
Here we should test the `findAllUsers` endpoint, right?

2020-12-16 11:08 UTC, Rostislav013 commented on test/controllers/user.test.ts
> +  it.skip('should get all users', async () => {
This one is for controllers still in progress. I would like to keep as it is now. 
Skip is temporary while doing other tests. Perfectly it should be without any skip.

2020-12-17 09:24 UTC, Chiranjibichapagain approved these changes
Looks good.

2020-12-17 12:07 UTC, MikeVedsted approved these changes

2020-12-17 12:15 UTC, MarinaFroes approved these changes
Great.

2020-12-17 12:15 UTC, MarinaFroes commented on test/services/user.test.ts
> +    const user = await createUser()
'should not get a non-existing _**user**_'

2020-12-17 12:21 UTC, merged