[refactor] Edit page
MikeVedsted/JoinMe pull request #207
Opened 2021-01-06 06:21 UTC by Rostislav013

**Attention. Your opinion is required.**

So we got a page for Account set up. It seems like it's the first one after creating an account. 
But what about just to edit user page at any time? If we use same set up account, it might a bit strange to get `For a better experience finding events, let's get your profile set up!` message every time.

Current flow: There is a page `AccountSetup` where is called component `AccountForm` to edit data.
What I want is to create a page `AccountForm`. **What do u think about that?**

2021-01-06 14:04 UTC, Chiranjibichapagain commented
Profile edit page and profile setup page should be different. I mean a
little different. Profile setup page can be visited only once by a user in
the beginning, which includes the message 'For a better..'  Profile edit
page won't have any message in it just can alter the information there.
Pages/ component names can be ProfileSetup and ProfileEdit.

On Wed, Jan 6, 2021 at 8:21 AM Rostislav Petrenko <notifications@github.com>
wrote:

> *Attention. Your opinion is required.*
>
> So we got a page for Account set up. It seems like it's the first one
> after creating an account.
> But what about just to edit user page at any time? If we use same set up
> account, it might a bit strange to get For a better experience finding
> events, let's get your profile set up! message every time.
>
> Current flow: There is a page AccountSetup where is called component
> AccountForm to edit data.
> What I want is to create a page AccountForm. *What do u think about that?*
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/MikeVedsted/JoinMe/pull/207
> Commit Summary
>
>    - [feat] Connect set up profile page
>
> File Changes
>
>    - *M* client/src/Routes.tsx
>    <https://github.com/MikeVedsted/JoinMe/pull/207/files#diff-123cb9322f0cdeda7647ee2a8b12b4acecabceaa40e98bfc1c335922bd1cc5cf>
>    (8)
>    - *M* client/src/pages/ProfilePage/index.tsx
>    <https://github.com/MikeVedsted/JoinMe/pull/207/files#diff-7082d600e5f2fe19e7a6164222bb75e55fbacae7baac4b5cfdcc52ab967bc396>
>    (2)
>
> Patch Links:
>
>    - https://github.com/MikeVedsted/JoinMe/pull/207.patch
>    - https://github.com/MikeVedsted/JoinMe/pull/207.diff
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/MikeVedsted/JoinMe/pull/207>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIONBKSBMFSHGQB7T24BPTSYP6QBANCNFSM4VXAWAYQ>
> .
>

2021-01-06 16:31 UTC, Rostislav013 commented
I will make then a file page/ProfileEdit. Where I will call AccountForm component. How does it sound? Is that what u meant?

2021-01-08 08:02 UTC, MikeVedsted commented
Make sure to reflect the latest changes to routes before undrafting this PR.

2021-01-13 12:34 UTC, MikeVedsted commented
@Rostislav013 check out the changes to address handling in #247 - I think you are dealing with the same issue

2021-01-14 09:56 UTC, Chiranjibichapagain approved these changes
:+1:

2021-01-14 11:17 UTC, MikeVedsted requested changes
for some reason, after updating address, birthday and gender the new values are not displayed when going back to the form. I think this might be because of the way you are using redux.  The address components aren't being updated in the state.

In general, if you are choosing to use redux, we should start refactoring to inject it everywhere.

2021-01-14 11:17 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/ProfileEdit.scss
> +  min-height: 100vh;
after the changes to the footer position, min-height shouldn't be necessary anymore

2021-01-14 11:17 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/ProfileEdit.scss
> +}
make sure this isn't repeated in both the component and the page

2021-01-14 11:17 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +      </div>
why is this check necessary?

2021-01-14 11:17 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +  }, [dispatch, user_id])
We are generally using hooks for this

2021-01-14 11:17 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +    !loading && (
We could implement a loading component. But please create an issue for it and remove the comment/implementation here, as it would need to be done in several places at the same time.

2021-01-14 11:17 UTC, MikeVedsted commented on src/services/user.ts
>        last_name = user.last_name,
Please add a message to the error on line 72

2021-01-14 11:17 UTC, MikeVedsted commented on src/services/user.ts
>      ])
It is not necessary to have two separate queries like this. Please follow the same logic as for updateEvent

2021-01-14 11:47 UTC, Rostislav013 commented on client/src/pages/ProfileEdit/index.tsx
> +      </div>
when they dont much user won't see a form. 
I fetch user data using user's id from cookies. Might be situation when userId is different from path but the page still shows correct user's data.

2021-01-15 03:44 UTC, Rostislav013 commented on client/src/components/AccountForm/index.tsx
>        <GoogleAutoComplete handleAddress={setAddress} />
Line 122 is different compare what is here. Specify again what do u mean

2021-01-15 03:49 UTC, Rostislav013 commented on client/src/pages/ProfileEdit/index.tsx
> +    !loading && (
Didn't you created it that issue [issue249](https://github.com/MikeVedsted/JoinMe/issues/249) ?

2021-01-15 04:29 UTC, Rostislav013 commented on client/src/components/AccountForm/index.tsx
>        />
Which PR/component?

2021-01-15 04:37 UTC, Rostislav013 commented on client/src/components/AccountForm/index.tsx
>        />
Used one from [PR247](https://github.com/MikeVedsted/JoinMe/pull/247/files), let me know if u meant this one

2021-01-15 07:37 UTC, Rostislav013 commented
> for some reason, after updating address, birthday and gender the new values are not displayed when going back to the form. I think this might be because of the way you are using redux. The address components aren't being updated in the state.
> 
> In general, if you are choosing to use redux, we should start refactoring to inject it everywhere.

I think problem was with not displaying it in inputs. Check again, I added displaying correctly

2021-01-17 11:46 UTC, MikeVedsted reviewed
I still think it is currently a weird mix of redux and no redux if we look at the app as a whole but that will probably get better when redux is more widely implemented. 

As we chatted about, your changes curently crash the app when trying to access account-setup, as there won't be a user in the state. Once that is fixed (and the current comments), I can approve your PR.

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/components/AccountForm/index.tsx
> +  }, [user])
if you change the user state to being a user object instead of an array, you won't have to always select [0]. This also makes sense if you think about that you should always _only_ have a single user's data available.

2021-01-17 11:46 UTC, MikeVedsted commented on src/services/user.ts
>      if (!user) {
Please remove console.log

2021-01-17 11:46 UTC, MikeVedsted commented on src/services/user.ts
> +
type should be inferred here, so no need to overwrite it with the any type. If anything, it should be `string | Address | undefined` as type

2021-01-17 11:46 UTC, MikeVedsted commented on src/services/user.ts
> +      !number && (number = 0)
It should now be possible to have number be part of the destructuring on line 88 and remove line 89+90. We no longer want to save a street number as 0 if none is submitted.

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/redux/reducers/user.ts
> +  },
Since only one user should be available, it would make more sense to have the UserState as an object instead of an array.

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/redux/reducers/user.ts
> +    }
If changing from array to object, these also need to be changed.

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +      <div className='page'>
Please don't use `page` as the class name. We are using specific naming on the other pages to avoid unintentional overlap of generic keywords and stylings (yes, AccountSetup page has the same issue but it must have slipped through..)

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +  }, [history, userId, user_id])
Could we somehow make a different type of route protection for this? I don't mean that you should do it now but maybe make an issue for it.. We could use something similar for edit events

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/hooks/useUser.ts
> +    try {
space between functions

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/hooks/useUser.ts
> +  }
I think you can also just use one function, and set the url in the ternary? 
That way, the whole function would be more DRY and would look like this:

```
const useUser = (userId: string) => {
  const dispatch = useDispatch()
  const [cookies] = useCookies(['user'])
  const { user_id } = cookies.user
  const [user, setUser] = useState<User>()
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchUser()
  }, [])

  const fetchUser = async () => {
    try {
      setLoading(true)
      const url =
        userId === user_id
          ? `/api/v1/users/${userId}`
          : `/api/v1/users/${userId}/public`
      const { data } = await axios.get(url)
      setUser(data)
      dispatch(addUser(data))
      setLoading(false)
    } catch (error) {
      console.log(error)
    }
  }

  return [user, loading]
}

export default useUser
```

2021-01-17 11:46 UTC, MikeVedsted commented on client/src/components/AccountForm/index.tsx
> +  useMemo(() => {
is useMemo the best option here? I think it should only be used for expensive functions, which setting the address isn't

2021-01-17 11:56 UTC, Rostislav013 commented on src/services/user.ts
> +
I didn't want to use `string | Address | undefined` as type, cuz it looks strange. `Any` type could be easier  spotted while refactoring types. But I'll use it then

2021-01-19 06:43 UTC, MikeVedsted approved these changes
I have some issues with the log out function in this PR. It might just be because you haven't pulled the latest changes to ProtectedRoute and refresh cookie.

2021-01-19 06:43 UTC, MikeVedsted commented on client/src/components/GoogleUserLogin/index.tsx
> +    console.log(diff)
Remove the console.log

2021-01-19 06:43 UTC, MikeVedsted commented on client/src/components/NavDropdown/index.tsx
>      history.push('/')
with the clickOutside implemented, you can remove line 29

2021-01-19 06:43 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +      </div>
Please use kebab-case for class names

2021-01-19 06:43 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/ProfileEdit.scss
> +
please add padding to the bottom as well, I can only see half of the submit button :)

2021-01-19 12:57 UTC, MikeVedsted commented on client/src/pages/ProfileEdit/index.tsx
> +    !loading && (
I did :)

2021-01-20 06:59 UTC, merged