[feat] profile page
MikeVedsted/JoinMe pull request #329
Opened 2021-01-26 08:21 UTC by nannadao

2021-01-26 10:17 UTC, MikeVedsted reviewed
I think you can DRY up the return of `/ProfilePage/index.tsx` and the styles (which you haven't touched on this PR).
Consider refactoring the data display to a component along the lines of `EventDataBox`

2021-01-26 10:17 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
>    const [hostedEvents] = useHostedEvents(userInfo.user_id)
the hosted events should always be for the requested user, so you can just use `userId` straight away

2021-01-26 10:17 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
>      getUserInfo()
This needs to be revised. Since we now have the current user in the store, there is not e.g. no need for the ternary in the url. We should also only fetch if the current user is not the same as the requested user, in which case it will always be the public data that is needed.

2021-01-26 10:17 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +          setUserInfo(data)
since you are setting userInfo after setting loaded, it will always flash the NotFound before populating.
the correct order is:

```
setUserInfo(data)
dispatch(clearErrors())
dispatch(setLoaded())
```

2021-01-26 10:17 UTC, MikeVedsted commented on client/src/pages/ProfilePage/index.tsx
> +        dispatch(setErrors(error.status, error.message))
set loaded last, to avoid flashing unintended content. 
```
} catch (error) {
  dispatch(setLoaded())
  dispatch(setErrors(error.status, error.message))
 }
```

2021-01-27 15:03 UTC, MikeVedsted requested changes
You do not need to have two separate pages. 
In your hook, you can check if the user in the store is the same as the requested one (from the params) and set the user info accordingly. 

You can then display the edit button based on the same check (maybe even make a helper function to do it or the state you already use...) as well as the other information.

I still think it would be better to have the infobox as a separate component to increase the ease of reading the page as a whole. 

As your code is currently, I am able to access public profile pages but the data does not populate.

 Make sure to pull the latest changes to scss.. You are missing a lot of new stuff on that front :)

2021-01-27 15:03 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
>      }
What does this do?

2021-01-27 15:03 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
>      }
you are setting the same style, so no need to repeat.

2021-01-27 15:03 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
> +    }
move include up

2021-01-31 21:33 UTC, nannadao commented on client/src/components/NotFound/NotFound.scss
>  }
In smaller phone dimension, the image is too big it will create unnecessary scrolling

2021-01-31 21:41 UTC, nannadao commented on client/src/pages/ProfilePage/ProfilePage.scss
>      }
To divide space equally between to title and 2 dividers

2021-01-31 22:45 UTC, nannadao commented on client/src/pages/ProfilePage/ProfilePage.scss
>      flex-basis: 70%;
I think since the info is to the left, it makes sense to keep the events to the left as well. I can style the title to the left so it can looks more coherent with the Personal Details title?

2021-02-01 08:26 UTC, MikeVedsted approved these changes

2021-02-01 08:26 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
>      flex-basis: 70%;
Yeah, that would be fine, just looks a bit weird when some things are centered and others aren't :))

2021-02-01 08:26 UTC, MikeVedsted commented on client/src/pages/ProfilePage/ProfilePage.scss
>      }
I meant the `>` selector. I've never seen it used before, so I'm just curious why, when `*` on its own should work the same

2021-02-01 10:49 UTC, merged