Feature activity creation
MikeVedsted/JoinMe pull request #48
Opened 2020-12-01 20:33 UTC by Chiranjibichapagain

Create Event functionality

2020-12-01 21:21 UTC, Rostislav013 commented on src/controllers/event.ts
> +import {Event} from '../types'
Could u fix imports, please

2020-12-01 21:21 UTC, Rostislav013 commented on src/routers/event.ts
> +router.post('/',isAuthenticated, createEvent)
Add space between `,` and `isAuthenticated`

2020-12-01 21:21 UTC, Rostislav013 commented on src/types.ts
> +  image:string
Add space between : and types

2020-12-01 21:21 UTC, Rostislav013 commented on src/services/event.ts
>  }
Is it ok to delete one of awaits?
To make it as:
```
const createEvent = async (event: Event) => {
  const newEvent = await pool.query(
          'INSERT INTO event (title, category, date, time, description, max_participants, address, expires_at, image) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *',
          [event.title, event.category, event.date, event.time, event.description, event.max_participants, event.address, event.expires_at, event.image]
      
  )
  return newEvent.rows
}
```

2020-12-01 21:29 UTC, MarinaFroes commented on src/routers/event.ts
> +router.post('/',isAuthenticated, createEvent)
Yes, and I think prettier + eslint were supposed to fix this. I'll have to check this rule.

2020-12-01 22:01 UTC, Rostislav013 approved these changes

2020-12-01 22:12 UTC, MarinaFroes reviewed
For the event creation, I think it's ok. 
But why does it include changes for google login as well? Were theses changes made on this same PR? If yes, we should consider moving them to a separate PR.

And about prettier and eslint, it seems you had some problems with them, is it correct?  `"jsx": "react"` changed back to `"jsx": "react-jsx"` when you tried to run it and you had problems with lack of spaces after commas and parenthesis? Please, let me know if you had issues because I'll need to  fix eslint rules. Thanks.

2020-12-01 22:18 UTC, MarinaFroes commented
> For the event creation, I think it's ok.
> But why does it include changes for google login as well? Were theses changes made on this same PR? If yes, we should consider moving them to a separate PR.
> 
> And about prettier and eslint, it seems you had some problems with them, is it correct? `"jsx": "react"` changed back to `"jsx": "react-jsx"` when you tried to run it and you had problems with lack of spaces after commas and parenthesis? Please, let me know if you had issues because I'll need to fix eslint rules. Thanks.

Oh, I think now I understand. Those changes for google login are from Nanna's PR but they weren't merged yet. Is that so?

2020-12-02 06:53 UTC, Chiranjibichapagain commented on client/tsconfig.json
>      "noFallthroughCasesInSwitch": true
this is not giving me any errors. Not sure if it is affecting the formatting or not.

2020-12-02 06:57 UTC, Chiranjibichapagain commented
yes, i had some misunderstanding about what we call an issue. As create
event should be authenticated i tried to check that as well at the same
time. Nana's new changes were not merged so i copied codes just to check
and pulled it later when merged.

On Wed, Dec 2, 2020 at 12:18 AM Marina Costa <notifications@github.com>
wrote:

> For the event creation, I think it's ok.
> But why does it include changes for google login as well? Were theses
> changes made on this same PR? If yes, we should consider moving them to a
> separate PR.
>
> And about prettier and eslint, it seems you had some problems with them,
> is it correct? "jsx": "react" changed back to "jsx": "react-jsx" when you
> tried to run it and you had problems with lack of spaces after commas and
> parenthesis? Please, let me know if you had issues because I'll need to fix
> eslint rules. Thanks.
>
> Oh, I think now I understand. Those changes for google login are from
> Nanna's PR but they weren't merged yet. Is that so?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MikeVedsted/JoinMe/pull/48#issuecomment-736855745>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIONBKRSXN2KSNP57PW6I3SSVTSNANCNFSM4UJQAJWQ>
> .
>

2020-12-02 09:26 UTC, MikeVedsted requested changes
A few things but overall good work 👍

2020-12-02 09:26 UTC, MikeVedsted commented on src/controllers/event.ts
>      console.log(error)
Please use the error handler to actually handle the error. 
Along the lines of: 

```
catch (error) {
    next(new NotFoundError('No events found', error))
  }
```

2020-12-02 09:26 UTC, MikeVedsted commented on src/controllers/event.ts
>      console.log(error)
Again, handle the error instead of console.log

2020-12-02 09:26 UTC, MikeVedsted commented on src/services/event.ts
> +  )
Please refactor to 

```
const { title, category, date, time, description, max_participants, address, expires_at, image } = event

  const newEvent = await pool.query(
    'INSERT INTO event (title, category, date, time, description, max_participants, address, expires_at, image) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *',
    [ title, category, date, time, description, max_participants, address, expires_at, image ]
  )
```

2020-12-02 09:26 UTC, MikeVedsted commented on src/types.ts
> +  image : string
did you or the linting add the spaces here? If possible, don't use the spaces. If the linting is the issue, reach out to Marina.
I think `date` and `time` can both be strings but address would also be a string since it is uuid v4, right?

2020-12-02 09:46 UTC, Chiranjibichapagain commented on src/types.ts
> +  image : string
rost wanted me to put the space.. :D i can remove it.

2020-12-02 09:52 UTC, Chiranjibichapagain commented on src/types.ts
> +  image : string
about address yes UUID is a string. will fix it

2020-12-02 09:56 UTC, Rostislav013 commented on src/types.ts
> +  image : string
It was like this: `image:string`.
I told about this way:  `image: string`
I didn't mean:  `image : string`
heh

2020-12-02 09:57 UTC, MikeVedsted commented on src/types.ts
> +  image : string
to be clear, it used to be `key:type` without any spaces. Now you have `key : type`  with space on both sides of the colon. Should be `key: type` with space only _between_ the colon and the type.

2020-12-02 09:58 UTC, MikeVedsted commented on src/types.ts
> +  image : string
> It was like this: `image:string`.
> I told about this way: `image: string`
> I didn't mean: `image : string`
> heh

two minds, one thought 😄

2020-12-02 09:59 UTC, MarinaFroes commented on src/types.ts
> +  image : string
I also agree with `key: type`. But it's supposed to be done automatically anyway. If you're allowed to do it in another way, I think I need to fix the rule. 🤔

2020-12-02 10:00 UTC, Chiranjibichapagain commented on src/types.ts
> +  image : string
okay  :D understood!

2020-12-02 10:42 UTC, MikeVedsted approved these changes
Great! 👍 
Thanks for the changes.

2020-12-02 10:44 UTC, merged