[feat] Create button components
MikeVedsted/JoinMe pull request #73
Opened 2020-12-07 14:14 UTC by Chiranjibichapagain

Resuable button component created.

2020-12-07 16:17 UTC, MarinaFroes reviewed
Please, consider doing a few adjustments based on my comments bellow.

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/components/Button/Button.scss
> +
The buttons look good, but we should follow BEM methodology for the class names.

In that case, `button` is the block, but we have modifiers for `primary`, `secondary` and `default`.
We also need modifiers to change the width of the button and borders, right? I've noticed that the buttons on the `aside`, `form` and `header` (main page) are different. 
We need to have modifiers for all those cases, as I understand. I am not sure if we need `element` in this case, though. 

And please, remember to use `&` to add the styles for the modifiers (and elements if necessary).

```css
.button {
  /* some styles */

  &--primary {
    /* some styles */
  }

  &--secondary {
     /* some styles */
   }

  /* other modifiers */
}
```

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/components/Button/index.tsx
> +// for style pass in "primary" | "secondary" | "default"; for handleClick pass in the function name.
I think we can remove the comments because we have types and they already tell us what values we can pass to those props.

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/App.tsx
>  // import Routes from './Routes'
Please, delete commented code. We can add it again when necessary.

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/types.ts
> +  style: string
For `style`, please add only the possible values: `primary`, `secondary` and `default`.
This way it's easier to find out what should I pass to this prop and we can't add new values.

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/components/Button/Button.scss
> +    color:#f2f2f2;
I think it's a good idea to create variables for the colours, it's easier to maintain and we don't need to remember the hex, but only the alias. We should have a file with all the colours for the project.

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/components/Button/Button.scss
> +    height:35px;
The buttons on the page have many different widths, right? We need to consider that on the specific modifiers.

2020-12-07 16:17 UTC, MarinaFroes commented on client/src/types.ts
> +  type: ButtonTypes
Do you think we will use `ButtonTypes` somewhere else? Because if not, it would be better to just have `type: 'button' | 'submit' | 'reset'`. If we do this, we can see the possible values when hovering the mouse over the props in the `Button` component.

2020-12-07 17:07 UTC, MikeVedsted requested changes
I think Marina hits the nail on the head here regarding the guidelines. 
Let's use the functionality we actually get from scss to keep the code maintainable by separating out variables and mixins where possible.

2020-12-07 17:07 UTC, MikeVedsted commented on client/src/components/Button/Button.scss
> +    background-color: #E03600;
let's use custom variables for the colors.

2020-12-07 17:07 UTC, MikeVedsted commented on client/src/components/Button/Button.scss
> +    font-family: 'Roboto', sans-serif;
let's also set global font families

2020-12-08 16:34 UTC, Chiranjibichapagain commented on client/src/components/Button/Button.scss
> +    height:35px;
i created two more modifiers; large and largeActive.

2020-12-08 18:55 UTC, MarinaFroes requested changes
Please, consider my comments bellow. 
If you want, you can copy and paste the example I added in your `Button.scss` file. 😄

2020-12-08 18:55 UTC, MarinaFroes commented on client/src/components/Button/Button.scss
> +}
The properties that all of them have in common, stay in the `.button` block, please check example bellow (you can copy and paste it).
I think maybe the most logical way would be not having the modifier `--default`, using its properties as the `button` block and then the other modifiers would change the necessary properties. But considering it's almost done, I think we can just do this adjustments and move on to the next component.

I also added the variables for font-sizes in the example. And I've changed the `--largeActive` modifier to `--large-active`. In the contributions guidelines, we decided to use one`-` to separate words in the block, element or modifier, like this : `block-name__elem-name--mod-name`. 😄 

```
.button {
  font-family: $roboto;
  border-style: none;
  border-radius: 4px;

    &--primary {
        background-color: $primary;
        width: 128px;
        height: 35px;
        font-size: $text;
        color: $textLight;
        transition: 0.3s ease-in-out;
    }

    &--primary:hover{
        background-color: white;
        border: 1px solid $primary;
        color: $primary
    }

    &--secondary {
        background-color: $secondary;
        width: 128px;
        height: 35px;
        font-size: $text;
        color: $textDark;
        transition: 0.3s ease-in-out;
    }

    &--secondary:hover{
        background-color: white;
        border: 1px solid $secondary;
        color: $secondary
    }

    &--default {
        background-color: $default;
        width: 128px;
        height: 35px;
        font-size: $text;
        color: $textLight;
        transition: 0.3s ease-in-out;
    }

    &--default:hover{
        background-color: white;
        border: 1px solid $default;
        color: $default
    }

    &--large-active {
        background-color: $primary;
        width: 327px;
        height: 50px;
        font-size: $sub-head;
        color: $textLight;
        text-align: left;
        padding: 0px 10px
    }

    &--large {
        background-color: $secondary;
        width: 327px;
        height: 50px;
        font-size: $sub-head;
        color: $textDark;
        text-align: left;
        padding: 0px 10px
    }
} 
```

2020-12-08 18:55 UTC, MarinaFroes commented on client/src/types.ts
> +  handleClick: () => void
Please, change `largeActive` to `large-active`.

2020-12-09 07:29 UTC, MikeVedsted approved these changes
Not a big fan of setting sizes with for the buttons with pixels but I think we can move on for now, and refactor some of this when addressing responsiveness.

2020-12-09 07:29 UTC, MikeVedsted commented on client/src/SCSS/_config.scss
> -
For some reason I can't add this comment to line 1-2 but that is where it goes..
It is only necessary to have line two, where you import both fonts. Line 1 can be removed.

2020-12-09 07:32 UTC, MarinaFroes approved these changes
It seems much better, thanks. 🏅 
Please, include the hover for the secondary modifier and I think we're good to go.

2020-12-09 07:32 UTC, MarinaFroes commented on client/src/components/Button/Button.scss
> +
You forgot the `hover` for the secondary modifier.

2020-12-09 08:15 UTC, Rostislav013 approved these changes

2020-12-09 08:24 UTC, merged