[feat] Add landing page
MikeVedsted/JoinMe pull request #96
Opened 2020-12-11 10:57 UTC by Chiranjibichapagain

Responsive landing page created

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/Button/Button.scss
> +  cursor:pointer;
Space after :  like  `cursor: pointer;`

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/Button/Button.scss
> +  cursor:pointer;
:shipit:

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/Button/Button.scss
> +    }
Space in `height: 65px`. Does it need `;` in the end?

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/Button/Button.scss
>      }
Does it need `;` in the end?

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/Button/Button.scss
>      }
Does it need `;` in the end?

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +  background-image: url(../../Assets/football.jpg);
Space in `height: 100vh;`

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +      display: flex;
Space in  ` width: 100vw;`

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +       position: absolute;
Space in  `height: 350px;`

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +       left:30vw;
Add spacing

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +       left:50vw;
Fix spacing

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +       color:$textLight
Fix spacing lines 50 and 56

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +       color:$textDark
Fix spacing

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +       display:flex;
Fix spacing

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +@media only screen and (max-width:1024px) {
Remove extra space

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +@media only screen and (max-width:768px) {
Add extra space between

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +}
Fix spacing

2020-12-11 12:12 UTC, Rostislav013 commented on client/src/components/LandingPage/LandingPage.scss
> +
Remove extra space

2020-12-11 12:16 UTC, Rostislav013 commented
Are we going to create a folder page where we will create files for pages? If it so, shall u move landing page into that folder and add route for that?

2020-12-11 12:51 UTC, MikeVedsted requested changes

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +  align-items: center;
you are repeating these three lines several times, and this is a pretty common configuration to center things, so please make a mixin for this instead.

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +  background-color: rgb(192, 251, 255);
why this color? 😬 
Maybe use one of the colors you have defined in the color scheme? And it only serves as a fallback, right? So maybe a dark and a light fallback variable would be appropriate.

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +  }
this can be inherited from the parent

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +   }
Please revise to follow BEM standards, so you have `__circle` as the element as well as  `--left` and `--right` as the modifiers. 

Something along these lines: 

```
...
&__circle {
  (mixin mentioned above) 
  width: 350px;
  height:350px;
  position: absolute;  
  top:25vh;
  background-color: #e03400c2; // CHANGE TO A THEME VARIABLE
  border-radius: 50%;
  &--left{
    left:25vw;
   }
  &--right {
    left:50vw;
  }
}
...
```

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +       align-items: center;
This is also repeated and a common configuration, please make a mixin

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +  background-color: rgb(192, 251, 255);
Why this color? 😬 
This is just a fallback color, right? So maybe something from the color scheme would be better, or even better, have a dark and light fallback defined in the variables.

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +  align-items: center;
You are are repeating this several times, so make a mixin instead.

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +  }
this can be inherited from the parent

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +   }
Please refactor this, to follow the BEM framework.
Ideally, you would have `__circle` as the element and `--left` and `--right` as the modifiers. That will also dry up your code a lot to follow this in general.

Something along these lines: 

```
...
&__circle {
    (mixin as mentioned above)
    width: 350px;
    height: 350px;
    position: absolute;
    top: 25vh;
    background-color: #e03400c2; // CHANGE TO A THEME VARIABLE
    border-radius: 50%;
    
    &--left {
        left:30vw;
    }

    &--right {
        left:50vw;
    }
}
...
```

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +   }
revise to follow BEM framework, so `--highlight `is a modifier of `__text`.

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +   }
I think you might clash with the styling of the component if you do it this way? At least for `justify-content`, right?

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +
remove 2 extra empty lines

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +@media only screen and (max-width:1024px) {
space out

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +       }
remember these for refactoring suggestion above

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +}
add empty line

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +       }
... and remember these as well 😄

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/LandingPage.scss
> +}
... and here. And remove extra empty line

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/index.tsx
> +          </p>
This should be dynamic

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/index.tsx
> +    <div className="body">
I think we can move some of the body stylings to apply to the entire app, so we won't have to wrap each page but we can refactor this later..

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/LandingPage/index.tsx
> +          </p>
sounds like a different kind of matching site 😂 
But this should also be dynamic, ideally. Leave it for now I guess..

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/Button/Button.scss
> +@media only screen and (min-width: 768px) and (max-width:1024px) {
add space after `max-width:`

2020-12-11 12:51 UTC, MikeVedsted commented on client/src/components/Button/Button.scss
> +    }
because it is the last, it will work - but please add it anyway 😄

2020-12-11 12:53 UTC, MikeVedsted commented
> Are we going to create a folder `pages` where we will create files for pages? If it so, shall u move landing page into that folder and add route for that?

Yes, please!

2020-12-13 20:05 UTC, Chiranjibichapagain commented on client/src/components/LandingPage/LandingPage.scss
> +   }
To center the button, i have created a div and put the button as a child.  So i think there won't be any problem.

2020-12-13 21:04 UTC, Chiranjibichapagain commented on client/src/components/LandingPage/index.tsx
> +          </p>
couldn't find the list of categories. can do it later.

2020-12-14 09:39 UTC, Rostislav013 approved these changes

2020-12-14 10:38 UTC, MikeVedsted approved these changes

2020-12-14 10:41 UTC, merged